services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hotel
      POSTGRES_PASSWORD: hotel
      POSTGRES_DB: hotel_mvp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
